### ISSUE TITLE
Change Value Statements to Outcomes

### ISSUE THREAD

**Issue by continuouslee** [castingclouds/refinery#1]
Talking to @jonkernPA, I like using the word outcomes compared to value statements.  It also would allow for a nice card UI for outcomes.  we should probably have some discussions around outcomes too.

- [x] change database table to outcomes
- [x] update the UI
- [ ] iterate on concept of outcomes and how to measure them

**Comment by JonKernPA** [comment]
I also like to track some form of metric once the "feature" goes live. In some cases, I also track actual feature usage in the app. And then track the outcome metrics -- whatever they may be.

Think of it as a "closed loop" approach. Don't just ship features. Ship "outcomes" :-)

- Posit an hypothesis of an expected outcome
- describe the feature(s)/initiative
- describe the likely metrics to capture
- once the feature transitions to being "deployed"
  - Track the metrics
- Then you can give it a thumbs up/down at some future date (6 months post-deploy?)
